packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - "@sentry/cli"
  - bcrypt
  - browser-tabs-lock
  - esbuild
  - msgpackr-extract
  - onnxruntime-node
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
