import { CollectionFieldSchema } from 'typesense/lib/Typesense/Collection';
import { CollectionCreateSchema } from 'typesense/lib/Typesense/Collections';

export const issueSchema: CollectionCreateSchema = {
  name: 'issues',
  fields: [
    { name: 'id', type: 'string' },
    { name: 'teamId', type: 'string' },
    { name: 'number', type: 'int32' },
    { name: 'numberString', type: 'string' },
    { name: 'issueNumber', type: 'string' },
    { name: 'title', type: 'string' },
    { name: 'description', type: 'string' },
    { name: 'descriptionString', type: 'string' },
    { name: 'stateId', type: 'string' },
    // Workflow category of the current state (COMPLETED, STARTED, …), faceted
    // so a search can be restricted to resolved work.
    { name: 'stateCategory', type: 'string', facet: true },
    // Concatenated text of every non-deleted comment — fixes are described in
    // comments, so they have to be searchable and part of the embedding.
    { name: 'commentsText', type: 'string' },
    // Best guess at the comment explaining how the issue was resolved.
    { name: 'resolutionText', type: 'string' },
    { name: 'workspaceId', type: 'string' },
    { name: 'assigneeId', type: 'string' },
  ],
  default_sorting_field: 'number',
};

/**
 * Embeddings are generated by typesense itself from the listed fields, using a
 * model that runs in-process. No issue content leaves the deployment.
 */
export const typesenseEmbedding: CollectionFieldSchema = {
  name: 'embeddings',
  type: 'float[]',
  embed: {
    from: ['issueNumber', 'title', 'description', 'commentsText'],
    model_config: {
      model_name: 'ts/all-MiniLM-L12-v2',
    },
  },
};

/**
 * The knowledge bank: page bodies and standing entries in one collection, so a
 * hit can be either a section of a document or a single asserted fact.
 *
 * The same in-process embedding model backs this. It matters more here than it
 * does for issues: a knowledge bank collects exactly the things a team keeps
 * out of a tracker — architecture decisions, why a customer left, what broke
 * last time — and none of it leaves the deployment.
 *
 * **The facet flags are the load-bearing part of this schema.** `group_by`
 * composes with vector search but works only on fields declared `facet: true`
 * at creation time, and typesense's alter endpoint cannot backfill an embedding
 * field, so adding a facet later forces the drop-and-rebuild path. Everything
 * grouping or triage could plausibly need is faceted up front.
 */
export const pageSchema: CollectionCreateSchema = {
  name: 'pages',
  fields: [
    { name: 'id', type: 'string' },
    { name: 'workspaceId', type: 'string' },
    // 'page' or 'entry'. A caller has to know whether it is reading agreed
    // narrative or one agent's assertion — they carry different authority.
    { name: 'kind', type: 'string', facet: true },
    // The flood-control axis: group_by pageId caps how much of a result set a
    // single busy page can occupy.
    { name: 'pageId', type: 'string', facet: true },
    { name: 'pageTitle', type: 'string' },
    { name: 'entryId', type: 'string' },
    { name: 'title', type: 'string' },
    { name: 'content', type: 'string' },
    // Faceted for triage: "24 from claude-opus-5 scoped apps/server/prisma".
    { name: 'scope', type: 'string', facet: true },
    { name: 'status', type: 'string', facet: true },
    { name: 'sourceUserId', type: 'string', facet: true },
    // Booleans rather than emptiness checks on the strings above, because
    // `_eval` needs a filter it can evaluate and `scope:!=''` is not one.
    { name: 'verified', type: 'bool', facet: true },
    { name: 'scoped', type: 'bool', facet: true },
    // Demonstrated usefulness, refreshed from postgres on re-index.
    { name: 'retrievalCount', type: 'int32' },
    // Coarse bucket ("2026-07") so recency can be faceted without turning every
    // distinct timestamp into its own facet value.
    { name: 'updatedBucket', type: 'string', facet: true },
    { name: 'updatedAt', type: 'int64' },
  ],
  default_sorting_field: 'retrievalCount',
};

export const pageEmbedding: CollectionFieldSchema = {
  name: 'embeddings',
  type: 'float[]',
  embed: {
    // Deliberately narrow. The `issues` collection embeds number, title,
    // description and every comment as one blob, which is why an exact
    // restatement of a title can score a *worse* vector distance than an
    // unrelated issue — matching one field still leaves most of the vector
    // different. An entry is one short claim, so its embedding should be a far
    // tighter fit. See SIMILARITY_MEASUREMENT_NOTE.
    from: ['title', 'content', 'scope'],
    model_config: {
      model_name: 'ts/all-MiniLM-L12-v2',
    },
  },
};

export const PAGE_QUERY_BY = 'title,content,scope,pageTitle,embeddings';

/**
 * How many documents one page may contribute to a result set.
 *
 * This is the single most important control in the design, because it is the
 * one that still holds when every other gate has failed. A page carrying fifty
 * entries contributes three. It decouples "the bank is messy" from "retrieval
 * is degraded" — an ungroomed bank still returns useful context, which buys
 * time to fix the mess rather than losing trust in the feature first.
 */
export const KNOWLEDGE_GROUP_LIMIT = 3;

/**
 * Ranking, expressed inside the query rather than re-sorted in Node.
 *
 * `_eval` scores conditionally during the search, so it composes with grouping
 * — a Node-side re-sort would reorder rows typesense had already grouped and
 * truncated, which is a different (and wrong) answer. Verified knowledge beats
 * unverified, and a narrowly-scoped fact beats a page-level one because it is
 * the one that actually applies to what the caller is doing.
 */
export const KNOWLEDGE_SORT_BY =
  '_text_match:desc,_eval([(verified:true):2,(scoped:true):1]):desc,retrievalCount:desc';

/** Facets the review rail opens on, before it shows a single row. */
export const KNOWLEDGE_FACET_BY = 'sourceUserId,scope,status,kind';

/**
 * A measured warning, kept next to the code it constrains.
 *
 * Tested against the live `issues` collection on typesense 27.1: an exact
 * restatement of an existing issue title scored a *greater* vector distance
 * (0.53) than an unrelated issue (0.47). Cosine distance from this model, over
 * a multi-field blob, is not a duplicate detector.
 *
 * Entries embed one short claim rather than a blob and should behave
 * considerably better — but "should" is not "does". Nothing here rejects a
 * write on a distance threshold; near matches are *returned to the caller*,
 * which puts the judgment in a model comparing two short facts, where it
 * belongs. Measure self-similarity on real entry text before any threshold
 * becomes load-bearing anywhere.
 */
export const SIMILARITY_MEASUREMENT_NOTE =
  'Vector distance is not calibrated for dedup here; near matches are returned, never auto-rejected.';

/** Distance ceiling for "entries that look like this one", used for dedup hints. */
export const KNOWLEDGE_NEAR_MATCH_DISTANCE = 0.75;

export interface KnowledgeSearchHit {
  id: string;
  kind: 'page' | 'entry';
  pageId: string;
  pageTitle: string;
  entryId: string | null;
  title: string;
  content: string;
  scope: string | null;
  status: string;
  sourceUserId: string | null;
  verified: boolean;
  retrievalCount: number;
  distance?: number;
  relevanceScore?: number;
}

export interface KnowledgeSearchResult {
  hits: KnowledgeSearchHit[];
  /** Counts by source, scope, status and kind — what bulk triage is built on. */
  facets: Record<string, Record<string, number>>;
  found: number;
}

/** Fields the running code depends on; a collection missing any is stale. */
export const requiredPageFields = pageSchema.fields
  .map((field) => field.name)
  .filter((name) => name !== 'id');

/**
 * Fields a free-text issue search matches against. Listing `embeddings` makes
 * typesense run a hybrid search: keyword matching over the text fields, fused
 * with a vector search over the embedding it generates from the query.
 */
export const ISSUE_QUERY_BY =
  'numberString,issueNumber,title,descriptionString,commentsText,embeddings';

/**
 * Cosine-distance ceiling for "issues similar to this one".
 *
 * The built-in MiniLM model produces noticeably higher distances than the
 * 1024-dim hosted model this code was originally written against — on a real
 * workspace, clearly related issues sit around 0.65-0.70 and unrelated ones
 * from 0.77 up, where the previous 0.5 ceiling matched nothing at all. Tuned
 * on a small corpus, so treat it as a starting point rather than a constant of
 * nature.
 */
export const SIMILAR_ISSUE_DISTANCE_THRESHOLD = 0.7;

export interface IssueSearchHit {
  id: string;
  title: string;
  description: string;
  descriptionMarkdown: string;
  descriptionString: string;
  stateId: string;
  stateCategory: string;
  resolutionSnippet: string;
  teamId: string;
  number: number;
  issueNumber: string;
  workspaceId: string;
  assigneeId: string;
  distance?: number;
  relevanceScore?: number;
}

/**
 * Fields the running code depends on; a collection missing any is stale.
 * `id` is excluded: typesense treats it as a reserved document key and never
 * reports it back in a collection's field list, so checking for it would mark
 * every collection stale and rebuild the index on every boot.
 */
export const requiredIssueFields = issueSchema.fields
  .map((field) => field.name)
  .filter((name) => name !== 'id');

/** How much comment text is indexed per issue (newest comments kept). */
export const MAX_COMMENTS_TEXT_LENGTH = 20_000;

/** Length of the resolution excerpt returned with each search hit. */
export const RESOLUTION_SNIPPET_LENGTH = 500;
