-- A citation's judgment records the words it judged.
--
-- A judge reads an entry's claim against changed code. A person may reword
-- the entry afterwards, and the gardener must not act on a judgment of the
-- old words as if it were about the new ones. The judged claim is kept as
-- the entry's content hash.
--
-- One new nullable column. No existing row is written: a judgment made before
-- this column is read again before anything acts on it.
-- AlterTable
ALTER TABLE "PageEntryCitation" ADD COLUMN     "judgedContentHash" TEXT;
