/**
 * The two questions the host asks the guest about its own working tree.
 *
 * A shell script seeded into the guest rather than a command string built in
 * TypeScript, for the same reason the prompt is a file: nothing here is
 * assembled from anything a run supplies, so there is no interpolation to get
 * wrong, and somebody debugging a guest can read the thing that actually ran.
 *
 * Written for BusyBox, which is what the guest image ships. Every utility used
 * — `find`, `sed`, `sort`, `cmp`, `diff`, `sha256sum`, `xargs -0`, `head -c` —
 * is in the BusyBox applet set, and nothing relies on a GNU-only flag.
 *
 * **This is not a security control.** The agent has a shell and can rewrite
 * both this script and the pristine copy it compares against, so a determined,
 * injected agent can make the diff say whatever it likes. It does not matter:
 * the tree the host packs and pushes is the tree the human reads on the pull
 * request, and the reviewer agent is a quality control on top of that, not a
 * boundary underneath it. The value here is that an honest agent's reviewer
 * gets a diff instead of a directory listing, which is most of the difference
 * between a review and a guess.
 */

/** Where the pristine base tree is unpacked, beside the working copy. */
export const BASE_DIR = '/workspace/base';

/** Where the script lands, relative to `/workspace`. */
export const TREE_TOOLS_PATH = 'tree-tools.sh';

/**
 * Directories never worth comparing.
 *
 * Only ones that are generated by definition. `dist`, `build` and `target` are
 * deliberately absent: a repository is entitled to track them, and pruning a
 * tracked directory would hide a real change. Their noise, when a setup command
 * generates them, is bounded by the output cap instead.
 */
const PRUNED = [
  '.git',
  'node_modules',
  '.venv',
  '__pycache__',
  '.pytest_cache',
  '.mypy_cache',
  '.gradle',
  '.turbo',
  'coverage',
  '.pi',
  '.pi-session',
  '.vantik-run',
];

/** Bytes of diff the reviewer is given. Beyond this it is not reading, it is scrolling. */
const MAX_DIFF_BYTES = 200_000;

/** A single file bigger than this is reported as changed rather than shown. */
const MAX_FILE_BYTES = 40_000;

const PRUNE_EXPRESSION = PRUNED.map((name) => `-name ${name}`).join(' -o ');

export const TREE_TOOLS_SCRIPT = `#!/bin/sh
# Written by Vantik. Reports what the working tree became, for the reviewer.
set -u

# The guest sets neither, so these are the paths in every real run. They are
# overridable so the spec can point the script at a fixture and actually run it
# — this is shell that only ever executes inside a microVM, and untested shell
# in a place nobody looks is how a reviewer silently starts getting an empty
# diff.
BASE="\${VANTIK_BASE_DIR:-${BASE_DIR}}"
REPO="\${VANTIK_REPO_DIR:-/workspace/repo}"

list_repo() {
  cd "$REPO" 2>/dev/null || return 1
  find . \\( ${PRUNE_EXPRESSION} \\) -prune -o \\( -type f -o -type l \\) -print |
    sed 's|^\\./||' | LC_ALL=C sort
}

list_base() {
  cd "$BASE" 2>/dev/null || return 1
  find . \\( -type f -o -type l \\) -print | sed 's|^\\./||' | LC_ALL=C sort
}

# A content hash of everything the agent could have touched. Used only to spot
# a pass that changed nothing, so it needs to be stable, not cryptographic.
tree_hash() {
  ( cd "$REPO" 2>/dev/null || return 1
    list_repo | while IFS= read -r f; do
      if [ -L "$f" ]; then
        printf 'symlink:%s  %s\\n' "$(readlink "$f")" "$f"
      else
        sha256sum "$f" 2>/dev/null
      fi
    done
  ) | sha256sum | cut -d' ' -f1
}

tree_diff() {
  { list_base; list_repo; } | LC_ALL=C sort -u | while IFS= read -r f; do
    [ -n "$f" ] || continue

    a="$BASE/$f"
    b="$REPO/$f"

    # Determine type of each side: 'l' symlink, 'f' regular file, '-' absent.
    a_type='-'; [ -L "$a" ] && a_type='l' || { [ -f "$a" ] && a_type='f'; }
    b_type='-'; [ -L "$b" ] && b_type='l' || { [ -f "$b" ] && b_type='f'; }

    if [ "$a_type" = '-' ] && [ "$b_type" = '-' ]; then
      continue
    fi

    # Skip when both sides are identical.
    if [ "$a_type" = "$b_type" ]; then
      if [ "$a_type" = 'l' ]; then
        [ "$(readlink "$a")" = "$(readlink "$b")" ] && continue
      else
        cmp -s "$a" "$b" && continue
      fi
    fi

    if [ "$b_type" = '-' ]; then
      printf '=== %s (deleted) ===\\n' "$f"
      continue
    fi

    if [ "$b_type" = 'l' ]; then
      if [ "$a_type" = '-' ]; then
        printf '=== %s (new symlink -> %s) ===\\n' "$f" "$(readlink "$b")"
      else
        printf '=== %s (symlink -> %s) ===\\n' "$f" "$(readlink "$b")"
      fi
      continue
    fi

    size=$(wc -c < "$b" 2>/dev/null || echo 0)

    if [ "$size" -gt ${MAX_FILE_BYTES} ]; then
      printf '=== %s (changed, %s bytes — too large to show) ===\\n' "$f" "$size"
      continue
    fi

    if [ "$a_type" = '-' ]; then
      printf '=== %s (new file) ===\\n' "$f"
      diff -u /dev/null "$b" 2>/dev/null | tail -n +3
    else
      printf '=== %s ===\\n' "$f"
      diff -u "$a" "$b" 2>/dev/null | tail -n +3
    fi
  done
}

case "\${1:-}" in
  hash) tree_hash ;;
  diff) tree_diff | head -c ${MAX_DIFF_BYTES} ;;
  *) echo "usage: tree-tools.sh hash|diff" >&2; exit 2 ;;
esac
`;

/** The command that prints a stable hash of the working tree. */
export const TREE_HASH_COMMAND = `sh /workspace/${TREE_TOOLS_PATH} hash`;

/** The command that prints the working tree's changes against the base. */
export const TREE_DIFF_COMMAND = `sh /workspace/${TREE_TOOLS_PATH} diff`;
